spring.application.name=spring-todo-graph-api


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

#本番運用ではこちらを使用
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO

#何かエラーが起きていて原因をログから調査したい場合
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG


